name: cv-dragon
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=h6b3803e_1
  - aiohttp=3.8.3=py310h80987f9_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=py310h1fc3239_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=py310hca03da5_0
  - aws-c-common=0.6.8=h1a28f6b_0
  - aws-c-event-stream=0.1.6=hc377ac9_5
  - aws-checksums=0.1.11=h1a28f6b_1
  - aws-sdk-cpp=1.8.185=h4a942e0_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osxarm64_openblas
  - boost-cpp=1.73.0=h1a28f6b_12
  - bottleneck=1.3.5=py310h96f19d2_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=hb547adb_0
  - ca-certificates=2023.5.7=hf0a4a13_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.12.0=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - exceptiongroup=1.0.4=py310hca03da5_0
  - fastapi=0.95.2=pyhd8ed1ab_0
  - filelock=3.12.0=pyhd8ed1ab_0
  - frozenlist=1.3.3=py310h80987f9_0
  - fsspec=2023.5.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gflags=2.2.2=hc88da5d_1004
  - glog=0.5.0=h5c6a83d_0
  - grpc-cpp=1.46.1=h8e4afa7_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.17.1=pyhd8ed1ab_0
  - httpx=0.24.1=pyhd8ed1ab_0
  - huggingface_hub=0.14.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=68.2=hbdafb3b_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - krb5=1.19.3=hf9b2bbe_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libboost=1.73.0=h49e8a49_12
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.87.0=h0f1d93c_0
  - libcxx=16.0.4=h4653b0c_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.10=hbae9a57_4
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran5=12.2.0=h0eea778_31
  - libiconv=1.17=he4db4b2_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libprotobuf=3.20.3=h514c7bf_0
  - libssh2=1.10.0=hb80f160_2
  - libthrift=0.13.0=hd358383_6
  - libuv=1.44.2=he4db4b2_0
  - llvm-openmp=16.0.4=h1c12783_0
  - lz4-c=1.9.4=hb7217d7_0
  - multidict=6.0.2=py310h1a28f6b_0
  - multiprocess=0.70.14=py310hca03da5_0
  - ncurses=6.4=h313beb8_0
  - ninja=1.11.1=hffc8910_0
  - numexpr=2.8.4=py310hecc3335_1
  - numpy=1.24.3=py310hb93e574_0
  - numpy-base=1.24.3=py310haf87e8b_0
  - openblas=0.3.21=openmp_hf78f355_3
  - openssl=1.1.1t=h03a7124_0
  - orc=1.7.4=hdca1487_1
  - packaging=23.0=py310hca03da5_0
  - pandas=1.5.3=py310h46d7db6_0
  - pip=23.0.1=py310hca03da5_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py310hca03da5_1
  - pooch=1.7.0=pyha770c72_3
  - protobuf=3.20.3=py310h313beb8_0
  - pyarrow=11.0.0=py310hbfed03b_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pypdf2=2.11.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.3.1=pyhd8ed1ab_0
  - python=3.10.11=hc0d8a6c_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py310h1a28f6b_1
  - pytorch=1.13.1=cpu_py310h9a5eeca_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h80987f9_1
  - re2=2022.04.01=h6b3803e_0
  - readline=8.2=h1a28f6b_0
  - regex=2022.7.9=py310h1a28f6b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py310h59830a0_1
  - scipy=1.10.1=py310h20cbe94_1
  - sentencepiece=0.1.99=py310h48ca7d4_0
  - setuptools=66.0.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlite=3.41.2=h80987f9_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=hb8d0fd4_0
  - tokenizers=0.11.4=py310h5c5695e_1
  - tomli=2.0.1=py310hca03da5_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - transformers=4.29.2=pyhd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.0.2=pyhd8ed1ab_0
  - utf8proc=2.6.1=h1a28f6b_0
  - uvicorn=0.20.0=py310hca03da5_0
  - wheel=0.38.4=py310hca03da5_0
  - xxhash=0.8.0=h27ca646_3
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.1=py310h1a28f6b_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - pydantic==1.10.7
      - typing-extensions==4.6.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/cv-dragon
